"""
Django settings for pickpickles_project project.

Generated by 'django-admin startproject' using Django 6.1.
All sensitive configurations are loaded from .env file.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if present
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# ==============================================================================
# 1. Core Security & Application Settings
# ==============================================================================
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-default-change-in-production')

DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() in ('true', '1', 't')

# Allowed Hosts
raw_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [host.strip() for host in raw_hosts.split(',') if host.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1',
    'http://localhost',
    'https://www.pickpickles.xyz',
    'https://pickpickles.xyz',
    'http://www.pickpickles.xyz',
    'http://pickpickles.xyz',
]

env_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if env_csrf:
    for origin in env_csrf.split(','):
        cleaned = origin.strip()
        if cleaned and cleaned not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(cleaned)


# ==============================================================================
# 2. Installed Applications & Middleware
# ==============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store.apps.StoreConfig',
    'dashboard.apps.DashboardConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'pickpickles-cache',
        'TIMEOUT': 300,
    }
}


ROOT_URLCONF = 'pickpickles_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'pickpickles_project.wsgi.application'


# ==============================================================================
# 3. Database Configuration (PostgreSQL / SQLite Auto-detection)
# ==============================================================================
DB_ENGINE = os.environ.get('DB_ENGINE', '').strip().lower()
DB_NAME = os.environ.get('DB_NAME', '').strip()

is_postgres = (
    'postgres' in DB_ENGINE or
    DB_ENGINE in ('django.db.backends.postgresql', 'postgresql', 'postgres')
)

if is_postgres and DB_NAME:
    # Check if postgres driver (psycopg or psycopg2) is installed
    try:
        import psycopg  # noqa: F401
    except ImportError:
        try:
            import psycopg2  # noqa: F401
        except ImportError:
            is_postgres = False

if is_postgres and DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': os.environ.get('DB_USER', 'postgres').strip(),
            'PASSWORD': os.environ.get('DB_PASSWORD', '').strip(),
            'HOST': os.environ.get('DB_HOST', '127.0.0.1').strip(),
            'PORT': os.environ.get('DB_PORT', '5432').strip(),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '600')),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ==============================================================================
# 4. Authentication & Passwords
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LOGIN_URL = '/dashboard/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/dashboard/login/'


# ==============================================================================
# 5. Localization & Timezone
# ==============================================================================
LANGUAGE_CODE = os.environ.get('DJANGO_LANGUAGE_CODE', 'en-us')
TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'Asia/Dhaka')
USE_I18N = True
USE_TZ = True
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# 6. Static & Media Files (WhiteNoise Storage)
# ==============================================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# ==============================================================================
# 7. Third-party Tracking & Couriers (Strictly from .env)
# ==============================================================================
# Analytics
META_PIXEL_ID = os.environ.get('META_PIXEL_ID', '')
GOOGLE_ANALYTICS_ID = os.environ.get('GOOGLE_ANALYTICS_ID', '')

# Pathao Courier API
PATHAO_BASE_URL = os.environ.get('PATHAO_BASE_URL', 'https://api-hermes.pathao.com')
PATHAO_CLIENT_ID = os.environ.get('PATHAO_CLIENT_ID', '')
PATHAO_CLIENT_SECRET = os.environ.get('PATHAO_CLIENT_SECRET', '')
PATHAO_USERNAME = os.environ.get('PATHAO_USERNAME', '')
PATHAO_PASSWORD = os.environ.get('PATHAO_PASSWORD', '')
PATHAO_STORE_ID = os.environ.get('PATHAO_STORE_ID', '')

# Steadfast Courier API
_raw_sf_url = os.environ.get('STEADFAST_BASE_URL', 'https://portal.packzy.com/api/v1')
STEADFAST_BASE_URL = _raw_sf_url.replace('portal.steadfast.com.bd', 'portal.packzy.com') if _raw_sf_url else 'https://portal.packzy.com/api/v1'
STEADFAST_API_KEY = os.environ.get('STEADFAST_API_KEY', '')
STEADFAST_SECRET_KEY = os.environ.get('STEADFAST_SECRET_KEY', '')


# ==============================================================================
# 8. Production Security Hardening
# ==============================================================================
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'False').lower() in ('true', '1', 't')

if not DEBUG:
    SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'False').lower() in ('true', '1', 't')
    CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'False').lower() in ('true', '1', 't')
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'

    if SECURE_SSL_REDIRECT or os.environ.get('DJANGO_ENABLE_HSTS', 'False').lower() in ('true', '1', 't'):
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
