# Generated by Django 6.1 on 2026-08-23 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-jar', help_text='FontAwesome icon class name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('delivery_address', models.TextField(help_text='House, Road, Area, Landmark')),
                ('delivery_city', models.CharField(default='Dhaka', max_length=100)),
                ('delivery_zone', models.CharField(choices=[('INSIDE_DHAKA', 'Inside Dhaka (৳60 Home Delivery)'), ('OUTSIDE_DHAKA', 'Outside Dhaka / Nationwide (৳120 Courier)')], default='INSIDE_DHAKA', max_length=20)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=60.0, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery (COD)'), ('BKASH', 'bKash (Send Money / Payment)'), ('NAGAD', 'Nagad (Send Money / Payment)')], default='COD', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid (COD)'), ('PENDING_VERIFICATION', 'Pending bKash/Nagad Verification'), ('PAID', 'Payment Received & Verified'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=30)),
                ('payment_sender_number', models.CharField(blank=True, help_text='Customer bKash/Nagad number', max_length=20)),
                ('payment_trx_id', models.CharField(blank=True, help_text='bKash / Nagad Transaction ID', max_length=100)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed & In Queue'), ('PACKING', 'Packing Fresh Jars'), ('OUT_FOR_DELIVERY', 'Out for Delivery / Shipped'), ('DELIVERED', 'Delivered 🎉'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('customer_notes', models.TextField(blank=True, help_text='Customer special request')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes / rider info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('tagline', models.CharField(help_text="Catchy tagline, e.g., 'Classic NYC Deli Crunch with Garlic & Fresh Dill'", max_length=255)),
                ('description', models.TextField()),
                ('flavor_profile', models.CharField(default='Garlic, Dill Weed, Peppercorn, Mustard Seed', max_length=255)),
                ('pairing_suggestions', models.CharField(default='Cheeseburgers, Deli Sandwiches, Fried Chicken, Snacks', max_length=255)),
                ('cut_style', models.CharField(choices=[('SPEARS', 'Spears / Quartered'), ('CHIPS', 'Crinkle Cut Chips / Slices'), ('WHOLE', 'Whole Pickles'), ('RELISH', 'Sweet & Savory Relish')], default='SPEARS', max_length=20)),
                ('spice_level', models.CharField(choices=[('MILD', 'Mild & Refreshing 🌿'), ('MEDIUM', 'Medium Zest 🌶️'), ('HOT', 'Hot & Tangy 🔥'), ('NAGA', 'Fire Naga Hot 💣')], default='MILD', max_length=20)),
                ('crunch_rating', models.PositiveSmallIntegerField(default=5, help_text='Rating out of 5')),
                ('jar_weight_grams', models.PositiveIntegerField(default=500, help_text='Weight in grams (e.g. 500g)')),
                ('price_bdt', models.DecimalField(decimal_places=2, help_text='Price in BDT (৳)', max_digits=10)),
                ('original_price_bdt', models.DecimalField(blank=True, decimal_places=2, help_text='Strike-through price if on sale', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.CharField(blank=True, help_text='Optional fallback image URL or static asset path', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('stock_count', models.PositiveIntegerField(default=50)),
                ('ingredients', models.TextField(default='Fresh Cucumbers, Filtered Water, Organic Apple Cider Vinegar, Pure Cane Vinegar, Sea Salt, Fresh Garlic, Dill Weed, Mustard Seeds, Coriander, Black Peppercorn.')),
                ('shelf_life', models.CharField(default='6 months unopened. Keep refrigerated after opening.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('jar_weight_grams', models.PositiveIntegerField(default=500)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_location', models.CharField(default='Dhaka, BD', max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
