# Generated by Django 6.1 on 2026-08-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=130.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('INSIDE_DHAKA', 'Inside Dhaka (৳130 Delivery)'), ('OUTSIDE_DHAKA', 'Outside Dhaka / Nationwide (৳130 Courier)')], default='INSIDE_DHAKA', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(default='Always keep refrigerated for maximum crunch. Best enjoyed within 2–3 months.', max_length=150),
        ),
    ]
