# Generated by Django 6.1 on 2026-08-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_order_delivery_fee_alter_order_delivery_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='Fresh Cucumbers, Filtered Water, Pure Cane Vinegar, Himalayan Pink Salt, Fresh Garlic, Dill Weed, Mustard Seeds, Coriander, Black Peppercorn.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pairing_suggestions',
            field=models.CharField(default='Smash Burgers, Fried Chicken, Shawarma, Beef Tehari, Biryani, Bhuna Khichuri, Daal-Rice', max_length=255),
        ),
    ]
