# Generated by Django 4.2 on 2026-08-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bkash_payment_id',
            field=models.CharField(blank=True, help_text='Official bKash PGW Payment ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BKASH_ONLINE', 'bKash Direct Online Payment'), ('COD', 'Cash on Delivery (COD)'), ('BKASH', 'bKash (Send Money / Manual)'), ('NAGAD', 'Nagad (Send Money / Manual)')], default='BKASH_ONLINE', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid (COD)'), ('PENDING_PAYMENT', 'Pending bKash Online Payment'), ('PENDING_VERIFICATION', 'Pending Manual Verification'), ('PAID', 'Payment Received & Verified'), ('REFUNDED', 'Refunded'), ('FAILED', 'Payment Failed')], default='UNPAID', max_length=30),
        ),
    ]
