# Generated by Django 4.2 on 2026-09-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_bkash_payment_id_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('INSIDE_DHAKA', 'Inside Dhaka (৳150 Delivery)'), ('OUTSIDE_DHAKA', 'Outside Dhaka / Nationwide (৳150 Courier)')], default='INSIDE_DHAKA', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='cut_style',
            field=models.CharField(choices=[('SPEARS', 'Spears / Quartered'), ('CHIPS', 'Crinkle Cut Chips / Slices'), ('WHOLE', 'Whole Pickles'), ('RELISH', 'Sweet & Savory Relish')], default='CHIPS', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavor_profile',
            field=models.CharField(default='Garlic, Bay Leaf, Peppercorn, Mustard Seed', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='Fresh Cucumbers, Filtered Water, Pure Cane Vinegar, Himalayan Pink Salt, Fresh Garlic, Bay Leaf (Tejpata), Mustard Seeds, Coriander, Black Peppercorn.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tagline',
            field=models.CharField(help_text="Catchy tagline, e.g., 'Classic Artisanal Deli Crunch with Garlic & Whole Spices'", max_length=255),
        ),
    ]
