# Generated by Django 4.2 on 2026-09-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_delivery_fee_alter_order_delivery_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(default='Always keep refrigerated for maximum crunch. Best enjoyed within 1 month.', max_length=150),
        ),
    ]
