# Generated by Django 5.2.17 on 2026-09-12 15:07

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_shelf_life'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft deleted / moved to trash'),
        ),
    ]
