# Generated by Django 4.2 on 2026-09-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_options_alter_order_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='jar_weight_grams',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='jar_weight_grams',
            field=models.PositiveIntegerField(default=600, help_text='Weight in grams (e.g. 600g)'),
        ),
    ]
