# Generated by Django 4.2 on 2026-09-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitem_jar_weight_grams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('INSIDE_DHAKA', 'Inside Dhaka (৳70 Base + ৳20/extra kg)'), ('DHAKA_SUBURBS', 'Dhaka Suburbs - Savar, Gazipur, Narayanganj, Keraniganj (৳100 Base + ৳20/extra kg)'), ('OUTSIDE_DHAKA', 'Outside Dhaka / Nationwide (৳130 Base + ৳25/extra kg)')], default='INSIDE_DHAKA', max_length=20),
        ),
    ]
