# Generated by Django 4.2 on 2026-09-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_delivery_fee_alter_order_delivery_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pathao_consignment_id',
            field=models.CharField(blank=True, help_text='Pathao Consignment ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_order_status',
            field=models.CharField(blank=True, help_text='Status synced from Pathao Courier', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pathao_tracking_code',
            field=models.CharField(blank=True, help_text='Pathao Public Tracking Code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(default='Faridpur', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('INSIDE_FARIDPUR', 'Inside Faridpur (৳60 Base + ৳20/extra kg)'), ('DHAKA_CITY', 'Dhaka City (৳130 Base + ৳25/extra kg)'), ('OUTSIDE_DHAKA', 'Outside Dhaka & Faridpur / Nationwide (৳140 Base + ৳25/extra kg)')], default='INSIDE_FARIDPUR', max_length=30),
        ),
    ]
