# Generated by Django 4.2 on 2026-09-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_pathao_consignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(default='Dhaka', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('INSIDE_DHAKA', 'Inside Dhaka City (৳70 Base + ৳20/extra kg)'), ('OUTSIDE_DHAKA', 'Outside Dhaka / Nationwide (৳130 Base + ৳25/extra kg)')], default='INSIDE_DHAKA', max_length=30),
        ),
    ]
