# Generated by Django 6.1 on 2026-09-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_renumber_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('INSIDE_DHAKA', 'Inside Dhaka City'), ('OUTSIDE_DHAKA', 'Outside Dhaka (Nationwide)')], default='INSIDE_DHAKA', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Order Confirmed & In Queue'), ('PACKING', 'Packing Fresh Jars'), ('OUT_FOR_DELIVERY', 'Out for Delivery / Shipped via Courier'), ('DELIVERED', 'Delivered 🎉'), ('CANCELLED', 'Cancelled / Returned')], default='PENDING', max_length=30),
        ),
    ]
