# Generated by Django 4.2 on 2026-09-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_delivery_fee_alter_order_delivery_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='gross_weight_grams',
            field=models.PositiveIntegerField(default=850),
        ),
        migrations.AddField(
            model_name='product',
            name='gross_weight_grams',
            field=models.PositiveIntegerField(default=850, help_text='Gross weight for delivery in grams (e.g. 850g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='jar_weight_grams',
            field=models.PositiveIntegerField(default=600, help_text='Net Weight in grams (e.g. 600g)'),
        ),
    ]
