# Generated by Django 6.1 on 2026-09-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_orderitem_gross_weight_grams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock_threshold',
            field=models.PositiveIntegerField(default=15, help_text='Alert if stock falls below this number'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_stock_level',
            field=models.PositiveIntegerField(default=50, help_text='Ideal target inventory quantity'),
        ),
    ]
