# Generated by Django 6.1 on 2026-09-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_min_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_provider',
            field=models.CharField(blank=True, choices=[('PATHAO', 'Pathao Courier'), ('STEADFAST', 'Steadfast Courier')], default='PATHAO', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='steadfast_consignment_id',
            field=models.CharField(blank=True, help_text='Steadfast Consignment ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='steadfast_order_status',
            field=models.CharField(blank=True, help_text='Status synced from Steadfast Courier', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='steadfast_tracking_code',
            field=models.CharField(blank=True, help_text='Steadfast Public Tracking Code', max_length=100, null=True),
        ),
    ]
