# Generated by Django 6.1 on 2026-09-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_courier_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('INSIDE_DHAKA', 'Inside Dhaka City'), ('OUTSIDE_DHAKA', 'Outside Dhaka (Nationwide)')], db_index=True, default='INSIDE_DHAKA', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Order Confirmed & In Queue'), ('PACKING', 'Packing Fresh Jars'), ('OUT_FOR_DELIVERY', 'Out for Delivery / Shipped via Courier'), ('DELIVERED', 'Delivered 🎉'), ('CANCELLED', 'Cancelled / Returned')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BKASH_ONLINE', 'bKash Direct Online Payment'), ('COD', 'Cash on Delivery (COD)'), ('BKASH', 'bKash (Send Money / Manual)'), ('NAGAD', 'Nagad (Send Money / Manual)')], db_index=True, default='BKASH_ONLINE', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid (COD)'), ('PENDING_PAYMENT', 'Pending bKash Online Payment'), ('PENDING_VERIFICATION', 'Pending Manual Verification'), ('PAID', 'Payment Received & Verified'), ('REFUNDED', 'Refunded'), ('FAILED', 'Payment Failed')], db_index=True, default='UNPAID', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(db_index=True, default=50),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='store_order_created_cad692_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', '-created_at'], name='store_order_order_s_97474c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_phone'], name='store_order_custome_5fda04_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_deleted', 'order_status'], name='store_order_is_dele_64f4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='store_order_payment_83b142_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivery_zone'], name='store_order_deliver_cf7228_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_count', 'name'], name='store_produ_stock_c_6ede2b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-is_featured', 'name'], name='store_produ_is_feat_333e39_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_in_stock'], name='store_produ_is_in_s_7a44dc_idx'),
        ),
    ]
