# Generated by Django 6.1 on 2026-10-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_created_at_alter_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when order was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when parcel was delivered to customer', null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['delivered_at'], name='store_order_deliver_8e7292_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['confirmed_at'], name='store_order_confirm_953522_idx'),
        ),
    ]
