# Generated by Django 6.1 on 2026-10-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_confirmed_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_gender',
            field=models.CharField(choices=[('FEMALE', 'Female (মহিলা)'), ('MALE', 'Male (পুরুষ)'), ('UNKNOWN', 'Unspecified (অনির্ধারিত)')], db_index=True, default='UNKNOWN', help_text='Auto-detected customer gender from name', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_gender'], name='store_order_custome_c4a5ec_idx'),
        ),
    ]
