# Generated by Django 6.1 on 2026-10-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_customer_gender_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='store_order_custome_c4a5ec_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_gender',
        ),
    ]
