# Generated by Django 6.1 on 2026-10-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_order_store_order_custome_c4a5ec_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shelf_life',
            field=models.CharField(default='Always keep refrigerated for maximum crunch. Best enjoyed within 2 months.', max_length=150),
        ),
    ]
