# Generated by Django 6.1 on 2026-10-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_shelf_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pairing_suggestions',
            field=models.CharField(default='Smash Burgers, Fried Chicken, Shawarma, Beef Tehari, Biryani, Bhuna Khichuri, Steamed Rice', max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='store.product'),
        ),
    ]
