# Generated by Django 5.2.17 on 2026-08-24 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. 200pcs 500g Glass Jars with Gold Lids', max_length=200)),
                ('category', models.CharField(choices=[('RAW_MATERIAL', 'Fresh Cucumbers & Veggies 🥒'), ('PACKAGING', 'Glass Jars, Lids & Labels 🫙'), ('SPICES_BRINE', 'Vinegar, Garlic, Dill & Spices 🌿'), ('LOGISTICS', 'Courier & Rider Delivery Cost 🚚'), ('MARKETING', 'Digital Ads & Marketing 📢'), ('UTILITIES', 'Gas, Electricity & Kitchen Rent ⚡'), ('OTHER', 'Operational & Miscellaneous 📋')], default='RAW_MATERIAL', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Cost amount in BDT (৳)', max_digits=10)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('BANK', 'Bank Transfer')], default='CASH', max_length=20)),
                ('receipt_reference', models.CharField(blank=True, help_text='Invoice/Voucher # or bKash TrxID', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional details, supplier name, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
