# Generated by Django 6.1 on 2026-08-26 05:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_expense_category'),
        ('store', '0003_alter_product_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of jars damaged')),
                ('estimated_cost_per_jar', models.DecimalField(decimal_places=2, default=200.0, help_text='Cost per jar in BDT', max_digits=10)),
                ('total_loss_bdt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reason', models.CharField(choices=[('TRANSIT_BREAKAGE', 'Courier / Rider Transit Breakage 🚚'), ('KITCHEN_SPILL', 'Kitchen Prep / Production Spill 🥒'), ('SEAL_DEFECT', 'Cap / Vacuum Seal Defect & Leaking 🫙'), ('EXPIRED_SPOILED', 'Spoiled / Freshness Quality Issue 🌿'), ('RETURN_DAMAGED', 'Damaged in Customer Return 📦'), ('OTHER', 'Other Operational Loss 📋')], default='TRANSIT_BREAKAGE', max_length=50)),
                ('incident_date', models.DateField(default=django.utils.timezone.now)),
                ('order_ref', models.CharField(blank=True, help_text='Order # if courier related', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Details of incident, courier consignment, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_logs', to='store.product')),
            ],
            options={
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(choices=[('CUSTOMER_UNREACHABLE', 'Customer Phone Off / Unreachable 📵'), ('CUSTOMER_REFUSED', 'Customer Refused at Doorstep 🚪'), ('WRONG_ADDRESS', 'Incorrect Address / Area Not Covered 📍'), ('COURIER_DELAY', 'Courier Delayed / Customer Cancelled ⏳'), ('DAMAGED_IN_TRANSIT', 'Jar Broken / Leaked during Delivery 💥'), ('WRONG_ITEM', 'Wrong Variety / Flavor Sent 🫙')], default='CUSTOMER_REFUSED', max_length=50)),
                ('return_status', models.CharField(choices=[('RETURNING', 'Returning with Courier (ফেরত আসছে)'), ('RECEIVED_INTACT', 'Received Intact & Restocked (ভালো আছে ও স্টকে যোগ করা হয়েছে)'), ('RECEIVED_DAMAGED', 'Received Damaged / Broken (ভাঙা/নষ্ট অবস্থায় ফেরত)')], default='RETURNING', max_length=30)),
                ('courier_return_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Return fee charged by courier (৳)', max_digits=8)),
                ('is_restocked', models.BooleanField(default=False, help_text='Whether jars have been added back to Product stock')),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Courier consignment ID, rider remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='store.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
