# Generated by Django 4.2 on 2026-09-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_damagelog_orderreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Fresh Cucumbers & Veggies 🥒'), ('PACKAGING', 'Glass Jars, Lids & Labels 🫙'), ('SPICES_BRINE', 'Vinegar, Garlic & Whole Spices 🌿'), ('LOGISTICS', 'Courier & Rider Delivery Cost 🚚'), ('MARKETING', 'Digital Ads & Marketing 📢'), ('UTILITIES', 'Gas, Electricity & Kitchen Rent ⚡'), ('OTHER', 'Operational & Miscellaneous 📋')], default='RAW_MATERIAL', max_length=100),
        ),
    ]
