# Generated by Django 6.1 on 2026-09-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(help_text='e.g. 200pcs 600g Glass Jars with Gold Lids', max_length=200),
        ),
    ]
