# Generated by Django 6.1 on 2026-09-13 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_expense_title'),
        ('store', '0013_alter_order_delivery_fee_alter_order_delivery_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('RESTOCK', 'Production / Restocked 🥒 (+)'), ('ORDER_CONFIRMED', 'Order Confirmed / Sold 📦 (-)'), ('ORDER_CANCELLED', 'Order Cancelled / Restored 🔄 (+)'), ('DAMAGE_LOSS', 'Breakage / Spoilage Loss 💥 (-)'), ('RETURN_RESTOCKED', 'Customer Return Restocked 🔙 (+)'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment ✏️')], default='MANUAL_ADJUSTMENT', max_length=30)),
                ('quantity_delta', models.IntegerField(help_text='Stock difference e.g. +50 or -3')),
                ('previous_stock', models.IntegerField(default=0)),
                ('resulting_stock', models.IntegerField(default=0)),
                ('reference', models.CharField(blank=True, help_text='e.g. Batch #4, Order #ORD-2026-001, Damage Log #5', max_length=150)),
                ('notes', models.TextField(blank=True, help_text='Extra details or remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
