# Generated by Django 5.2.17 on 2026-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_stocklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='return_reason',
            field=models.CharField(choices=[('CUSTOMER_UNREACHABLE', 'Customer Phone Off / Unreachable 📵 (Customer Issue)'), ('CUSTOMER_REFUSED', 'Customer Refused at Doorstep 🚪 (Customer Issue)'), ('WRONG_ADDRESS', 'Incorrect Address / Area Not Covered 📍'), ('COURIER_DELAY', 'Courier Delay / RTO ⏳ (Courier Fault)'), ('DAMAGED_IN_TRANSIT', 'Broken / Leaked in Transit 💥 (Courier Fault)'), ('COURIER_FAULT', 'Courier Fault / Lost / Hub Misroute 🚚 (Courier Fault)'), ('WRONG_ITEM', 'Wrong Variety Sent 🫙 (Merchant Fault)')], default='CUSTOMER_REFUSED', max_length=50),
        ),
    ]
