# Generated by Django 4.2 on 2026-09-26 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_orderreturn_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagelog',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_logs', to='dashboard.expense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Fresh Cucumbers & Veggies 🥒'), ('PACKAGING', 'Glass Jars, Lids & Labels 🫙'), ('SPICES_BRINE', 'Vinegar, Garlic & Whole Spices 🌿'), ('LOGISTICS', 'Courier & Rider Delivery Cost 🚚'), ('MARKETING', 'Digital Ads & Marketing 📢'), ('UTILITIES', 'Gas, Electricity & Kitchen Rent ⚡'), ('DAMAGE_LOSS', 'Damaged & Broken Products Loss 💥'), ('OTHER', 'Operational & Miscellaneous 📋')], default='RAW_MATERIAL', max_length=100),
        ),
    ]
