# Generated by Django 4.2 on 2026-09-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_damagelog_expense_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_returns', to='dashboard.expense'),
        ),
    ]
