# Generated by Django 6.1 on 2026-09-30 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_orderreturn_expense'),
        ('store', '0017_alter_order_created_at_alter_order_customer_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='e.g. Batch #1, Batch #2, Winter Special 2026', max_length=150)),
                ('production_date', models.DateField(default=django.utils.timezone.now, help_text='Date when this batch was prepared/bottled')),
                ('notes', models.TextField(blank=True, help_text='Batch preparation notes, ingredients, brine formulation, or chef remarks')),
                ('total_cost_bdt', models.DecimalField(decimal_places=2, default=0.0, help_text='Total production cost for this batch in BDT', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-production_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of jars produced for this flavor')),
                ('unit_cost_bdt', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated cost per jar', max_digits=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='store.product')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.productionbatch')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
    ]
