# Generated by Django 6.1 on 2026-10-01 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_productionbatch_batchitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, help_text='Clean recipient phone number (e.g. 017XXXXXXXX)', max_length=20, unique=True)),
                ('customer_name', models.CharField(blank=True, help_text='Optional customer name for reference', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Optional IP address', null=True)),
                ('reason', models.CharField(default='Fake orders / prank harassment / repeated refusal', help_text='Reason for blocking', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active block status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklisted Customer',
                'verbose_name_plural': 'Blacklisted Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
