# Generated by Django 6.1 on 2026-10-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_blacklistedcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantity or weight purchased', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='sub_category',
            field=models.CharField(blank=True, help_text='Sub-category (e.g. Cucumber, Carrot, Jar, Vinegar)', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg (কেজি)'), ('gm', 'gm (গ্রাম)'), ('pcs', 'pcs (পিস/সংখ্যা)'), ('liter', 'liter (লিটার)'), ('ml', 'ml (মিলি)'), ('pack', 'pack (প্যাকেট)'), ('box', 'box (বক্স/কার্টন)'), ('other', 'other (অন্যান্য)')], default='pcs', max_length=20),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='dashboard.expensecategory'),
        ),
    ]
